### ISSUE TITLE
TypeScript types declaration file

### ISSUE THREAD

**Issue by geopic** [Vincit/objection-find#54]
This npm package needs a TypeScript types declaration file so that developers who enjoy writing with TS can use it with this package and have a better development experience. Would you like me to write one?

**Comment by kibertoad** [comment]
Yes, please!
Actually, I wouldn't mind converting the whole project to TS, since that is likely to be even easier. If you feel like taking up the task, you can use https://github.com/kibertoad/canned-enterprise-node/tree/master/typescript-template (but probably bump versions up) as a skeleton for TS project, although improvements over it are also welcome.

**Comment by geopic** [comment]
I'll look into it soon @kibertoad , thanks

**Comment by geopic** [comment]
I can start on the file now unless you are planning to migrate the whole project to TS imminently. It's simpler just to write a declaration file, I can help out in that way easy-peasy. :stuck_out_tongue:

**Comment by kibertoad** [comment]
@geopic Sure, I would appreciate that

**Comment by geopic** [comment]
Alright, I'll get started soon.

**Comment by kibertoad** [comment]
Types published in 2.1.0
