### ISSUE TITLE
How to import objection-find with typescript

### ISSUE THREAD

**Issue by marcpearson** [Vincit/objection-find#72]
1. import * as findQuery from 'objection-find
2. import findQuery from 'objection-find'

I got this error : TypeError: objection_find_1.default is not a function

The only it works:
const findQuery = require('objection-find')

Do i need to set something in my tsconfig.json

Could you write and example in the readme, thanks

**Comment by kibertoad** [comment]
Looks like we need to add the infamous triplet. Will release fixed version over weekend

**Comment by marcpearson** [comment]
And for now, what do i do

**Comment by kibertoad** [comment]
Have you tried named imports, though? import { findQuery } from 'objection-find'?

**Comment by marcpearson** [comment]
Typescript error ts(2614) : No member 'findquery' exported

**Comment by thisiskalnins** [comment]
For me

`import findQuery from 'objection-find';`

works, i think you need to enable "esModuleInterop" or "allowSyntheticDefaultImports" in tsconfig.

There is a problem for me tho. I've been using this package for a long time in js and it has been a blast! But now i've started a typescript project and when i use this, as i've been doing since begining, i get a confusing error.

`await findQuery(Model).build(req.query);`

I get: Property 'build' does not exist on type 'FindStatic<...>'. What am i doing wrong here or is there a error in type defs?

typescript@4.0.3
objection@2.2.3
objection-find@3.0.0

Thanks for this great package!

**Comment by kibertoad** [comment]
@thisiskalnins Yeah, types seem to be pretty broken, TBH. Trying to fix them now.

**Comment by kibertoad** [comment]
@marcpearson @thisiskalnins 3.0.1 is released and should work much better with TypeScript. Would appreciate if you could confirm if it works for you.

**Comment by thisiskalnins** [comment]
@kibertoad Well, everything that i had problems with, now seems to be working. Thanks! :+1:
